services:
  accounts:
    image: "sahilghadage5/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 900m
    networks:
      - bankapp
  loans:
    image: "sahilghadage5/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 900m
    networks:
      - bankapp
  cards:
    image: "sahilghadage5/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 900m
    networks:
      - bankapp
networks:
  bankapp:
    driver: "bridge"