server:
  port: 8090
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    database-platform: org.hibernate.dialect.H2Dialect
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    appname: loans
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "loans"
    description: "Bank App Loans Application"
    version: "1.0.0"