server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    database-platform: org.hibernate.dialect.H2Dialect
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"