server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: update
        show-sql: false
  sql:
      init:
        mode: always
