services:
  configserver:
    image: "sahilghadage5/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      SPRING_APPLICATION_NAME: "configserver"

  accounts:
    image: "sahilghadage5/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"

    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-base-config

  loans:
    image: "sahilghadage5/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"

    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-base-config

  cards:
    image: "sahilghadage5/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"

    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-base-config


networks:
  bankapp:
    driver: "bridge"
